"""remove password from user

Revision ID: 115c28c7ee8c
Revises: 2bbd54bb8ec1
Create Date: 2022-09-11 19:51:14.421869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '115c28c7ee8c'
down_revision = '2bbd54bb8ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=222), nullable=False))
    # ### end Alembic commands ###
