"""empty message

Revision ID: 19dd74b8ccbd
Revises: 
Create Date: 2022-09-12 16:27:17.382757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd74b8ccbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_extension',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('use_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['use_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_extension')
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
